### ISSUE TITLE
error when get the blowfish encryption key

### ISSUE THREAD

**Issue by limetyapple** [svanheulen/mhef#13]
then error information below:
```````````````
E:\limet\Desktop\mhef-master\tools>python get_mhx_key.py 192.168.1.110
connecting ...
    connected to 192.168.1.110 port 8000
getting process ...
    process id is 41
checking for object 1 ...
checking for object 2 ...
checking for key ...
Traceback (most recent call last):
  File "get_mhx_key.py", line 131, in <module>
    app.run()
  File "get_mhx_key.py", line 93, in run
    packet = self._read_packet()
  File "get_mhx_key.py", line 61, in _read_packet
    self._key = packet_data.decode().strip('\x00')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 0: invalid start byte
````````````````
the ntr version is 3.4 preview6 and mhx version is 1.3

**Comment by svanheulen** [comment]
Yeah, that script wont work with the newest MHX game update.
Use this homebrew app instead: https://github.com/svanheulen/mhx_data_manager
